networks:
  chat-bot-network:
    driver: bridge

volumes:
  mysql:
    name: chat-bot-mysql

services:
  mysql:
    container_name: ${CONTAINER_NAME}
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d/
    networks:
      chat-bot-network:
        aliases:
          - mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      
##   apiUrl: 'https://chat.systemart.com.ar'
## docker-compose up --build -d
