networks:
  chat-bot-network:
    driver: bridge

volumes:
  mysql:
    name: chat-bot-mysql
  chat-bot-app:
    name: chat-bot-app

services:
  node:
    container_name: Chat-Bot
    restart: on-failure
    build:
      context: .
    volumes:
      - chat-bot-app:/home/node/app/tmp
    ports:
      - "${PORT}:12345"
    networks:
      chat-bot-network:
        aliases:
          - mysql
  mysql:
    container_name: ${CONTAINER_NAME}
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${EXTERNAL_MYSQL_PORT}:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d/
    networks:
      chat-bot-network:
        aliases:
          - mysql

##   apiUrl: 'https://chat.systemart.com.ar'
## docker-compose up --build -d

